export const KEYS = {
  BOLA_EXTRA: "¡Bola extra!",
  GANA_LABEL: "¡Gana {label}!",
  TURBO: "¡Turbo!",
  TEXT_1_JUGADOR_VS_CPU: "1 Jugador vs CPU",
  TEXT_2_JUGADORES: "2 Jugadores",
  AMARILLO_AFECTA_A_AMBOS_JUGADORES_POR_IGUAL: "Amarillo: afecta a ambos jugadores por igual",
  COMO_JUGAR: "Cómo jugar",
  CONTROLES_INVERTIDOS: "Controles invertidos",
  CPU: "CPU",
  DIFICIL: "Difícil",
  ELEGI_LA_DIFICULTAD_DE_LA_CPU: "Elegí la dificultad de la CPU",
  ELEGI_UNA_OPCION_DE_CADA_GRUPO_Y_CONFIRMA_CON_ENTER: "Elegí una opción de cada grupo y confirmá con ENTER",
  ENTER_ESC_REANUDAR_M_VOLVER_AL_MENU: "ENTER / ESC: Reanudar M: Volver al menú",
  ENTER_O_CLIC_EMPEZAR: "ENTER o clic: Empezar",
  ENTER_EMPEZAR: "ENTER: Empezar",
  ENTER_VOLVER_AL_MENU: "ENTER: Volver al menú",
  ESC_PAUSAR_LA_PARTIDA_EN_CUALQUIER_MOMENTO: "ESC: pausar la partida en cualquier momento",
  FACIL: "Fácil",
  IMPOSIBLE: "Imposible",
  JUGADOR_1: "Jugador 1",
  JUGADOR_1_W_S_JUGADOR_2_FLECHAS_ARRIBA_ABAJO: "Jugador 1: W / S Jugador 2: Flechas arriba/abajo",
  JUGADOR_2: "Jugador 2",
  LLUVIA_DE_POWER_UPS: "Lluvia de power-ups",
  LOS_POWER_UPS_APARECEN_EN_EL_CENTRO_DE_LA_CANCHA_NLOS_ACTIVA_EL_PRIMERO_QUE_LOS_TOCA_CON_LA_PELOTA: "Los power-ups aparecen en el centro de la cancha.\\nLos activa el primero que los toca con la pelota:",
  NORMAL: "Normal",
  PALA_CHICA: "Pala chica",
  PALA_GRANDE: "Pala grande",
  PALA_LENTA: "Pala lenta",
  PALA_RAPIDA: "Pala rápida",
  PALETA_CENTRAL: "Paleta central",
  PARTIDA_A_10_PUNTOS: "Partida a 10 puntos",
  PARTIDA_A_5_PUNTOS: "Partida a 5 puntos",
  PARTIDA_A_7_PUNTOS: "Partida a 7 puntos",
  PAUSA: "PAUSA",
  PELOTA_CURVA: "Pelota curva",
  PELOTA_ZIGZAGUEANTE: "Pelota zigzagueante",
  PELOTA_INVISIBLE: "Pelota invisible",
  PUNTO_DOBLE: "Punto doble",
  REANUDAR: "Reanudar",
  ROJO_TE_PERJUDICA_A_VOS_O_BENEFICIA_AL_RIVAL: "Rojo: te perjudica a vos (o beneficia al rival)",
  VERDE_TE_BENEFICIA_A_VOS_O_PERJUDICA_AL_RIVAL: "Verde: te beneficia a vos (o perjudica al rival)",
  VOLVER_AL_MENU: "Volver al menú",

  // Modo Historia: pantallas.
  MODO_HISTORIA: "Modo Historia",
  NIVEL_N: "Nivel {n}",
  JEFE: "Jefe",
  JEFE_FINAL: "Jefe final",
  BLOQUEADO: "Bloqueado",
  GANA_EL_NIVEL_N_PARA_DESBLOQUEARLO: "Ganá el nivel {n} para desbloquearlo",
  FLECHAS_ELEGIR_ENTER_JUGAR_ESC_VOLVER: "Flechas: elegir   ENTER: jugar   ESC: volver",
  ESC_VOLVER: "ESC: volver",

  // Modo Historia: nombre, habilidad y frase de cada rival (src/data/levels.js).
  NOVATO: "Novato",
  SIN_TRUCOS_IDEAL_PARA_APRENDER: "Sin trucos: ideal para aprender.",
  TRANQUI_YO_TAMBIEN_ESTOY_APRENDIENDO: "Tranqui, yo también estoy aprendiendo.",
  APRENDIZ: "Aprendiz",
  UN_RIVAL_PAREJO_SIN_TRUCOS: "Un rival parejo, sin trucos.",
  YA_PRACTIQUE_ESTA_VEZ_NO_TE_LA_HAGO_FACIL: "Ya practiqué. Esta vez no te la hago fácil.",
  EL_MURO: "El Muro",
  SU_PALA_ES_ENORME_PERO_LENTA: "Su pala es enorme, pero lenta.",
  POR_ACA_NO_PASA_NADA: "Por acá no pasa nada.",
  VELOCISTA: "Velocista",
  LA_PELOTA_SALE_MAS_RAPIDO_Y_ACELERA_MAS: "La pelota sale más rápido y acelera más.",
  PESTANEA_Y_TE_LA_PERDISTE: "Pestañeá y te la perdiste.",
  LOS_GEMELOS: "Los Gemelos",
  DOS_PALAS_UNA_EN_EL_ARCO_Y_OTRA_ADELANTADA: "Dos palas: una en el arco y otra adelantada.",
  DOS_CONTRA_UNO_NO_ES_TRAMPA_SI_SOMOS_GEMELOS: "Dos contra uno no es trampa si somos gemelos.",
  TRIVELA: "Trivela",
  SUS_TIROS_CON_EFECTO_SE_CURVAN: "Sus tiros con efecto se curvan.",
  LE_PEGO_DE_AFUERA_DEL_PIE_SUERTE_ADIVINANDO: "Le pego de afuera del pie. Suerte adivinando.",
  ESTADIO: "Estadio",
  CANCHA_GRANDE_Y_CALCULA_DONDE_VA_A_LLEGAR_LA_PELOTA: "Cancha grande, y calcula dónde va a llegar la pelota.",
  BIENVENIDO_A_LA_CANCHA_GRANDE: "Bienvenido a la cancha grande.",
  SABOTEADOR: "Saboteador",
  CADA_TANTO_TE_INVIERTE_LOS_CONTROLES_O_TE_FRENA_LA_PALA: "Cada tanto te invierte los controles o te frena la pala.",
  TUS_CONTROLES_ANDAN_RARO_QUE_CASUALIDAD: "¿Tus controles andan raro? Qué casualidad.",
  TORMENTA: "Tormenta",
  DOS_PELOTAS_POR_RONDA_Y_LLUVIA_DE_POWER_UPS: "Dos pelotas por ronda y lluvia de power-ups.",
  ESPERO_QUE_TE_GUSTE_EL_CAOS: "Espero que te guste el caos.",
  EL_CAMPEON: "El Campeón",
  SUMA_TRUCOS_A_MEDIDA_QUE_TE_ACERCAS_A_GANARLE: "Suma trucos a medida que te acercás a ganarle.",
  LLEGASTE_LEJOS_ACA_SE_TERMINA: "Llegaste lejos. Acá se termina.",
};
