export const KEYS = {
  BOLA_EXTRA: "¡Bola extra!",
  GANA_LABEL: "¡Gana {label}!",
  TURBO: "¡Turbo!",
  TEXT_1_JUGADOR_VS_CPU: "1 Jugador vs CPU",
  TEXT_2_JUGADORES: "2 Jugadores",
  AMARILLO_AFECTA_A_AMBOS_JUGADORES_POR_IGUAL: "Amarillo: afecta a ambos jugadores por igual",
  COMO_JUGAR: "Cómo jugar",
  CONTROLES_INVERTIDOS: "Controles invertidos",
  CPU: "CPU",
  DIFICIL: "Difícil",
  ELEGI_LA_DIFICULTAD_DE_LA_CPU: "Elegí la dificultad de la CPU",
  ELEGI_UNA_OPCION_DE_CADA_GRUPO_Y_CONFIRMA_CON_ENTER: "Elegí una opción de cada grupo y confirmá con ENTER",
  ENTER_ESC_REANUDAR_M_VOLVER_AL_MENU: "ENTER / ESC: Reanudar M: Volver al menú",
  ENTER_O_CLIC_EMPEZAR: "ENTER o clic: Empezar",
  ENTER_EMPEZAR: "ENTER: Empezar",
  ENTER_VOLVER_AL_MENU: "ENTER: Volver al menú",
  ESC_PAUSAR_LA_PARTIDA_EN_CUALQUIER_MOMENTO: "ESC: pausar la partida en cualquier momento",
  FACIL: "Fácil",
  JUGADOR_1: "Jugador 1",
  JUGADOR_1_W_S_JUGADOR_2_FLECHAS_ARRIBA_ABAJO: "Jugador 1: W / S Jugador 2: Flechas arriba/abajo",
  JUGADOR_2: "Jugador 2",
  LLUVIA_DE_POWER_UPS: "Lluvia de power-ups",
  LOS_POWER_UPS_APARECEN_EN_EL_CENTRO_DE_LA_CANCHA_NLOS_ACTIVA_EL_PRIMERO_QUE_LOS_TOCA_CON_LA_PELOTA: "Los power-ups aparecen en el centro de la cancha.\\nLos activa el primero que los toca con la pelota:",
  NORMAL: "Normal",
  PALA_CHICA: "Pala chica",
  PALA_GRANDE: "Pala grande",
  PALA_LENTA: "Pala lenta",
  PALA_RAPIDA: "Pala rápida",
  PALETA_CENTRAL: "Paleta central",
  PARTIDA_A_10_PUNTOS: "Partida a 10 puntos",
  PARTIDA_A_5_PUNTOS: "Partida a 5 puntos",
  PAUSA: "PAUSA",
  PELOTA_ERRATICA: "Pelota errática",
  PELOTA_INVISIBLE: "Pelota invisible",
  PONG_CON_POWER_UPS: "PONG con Power-ups",
  PUNTO_DOBLE: "Punto doble",
  REANUDAR: "Reanudar",
  ROJO_TE_PERJUDICA_A_VOS_O_BENEFICIA_AL_RIVAL: "Rojo: te perjudica a vos (o beneficia al rival)",
  VERDE_TE_BENEFICIA_A_VOS_O_PERJUDICA_AL_RIVAL: "Verde: te beneficia a vos (o perjudica al rival)",
  VOLVER_AL_MENU: "Volver al menú",
};
